# Generated by Django 4.0.3 on 2022-03-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
