# Generated by Django 4.0.3 on 2022-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_locals'),
    ]

    operations = [
        migrations.AddField(
            model_name='locals',
            name='phonenumber',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
