# Generated by Django 4.0.3 on 2022-03-23 20:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_locals_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='locals',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='locals',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
